name: CI Coverage

on: [ push ]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: php-actions/composer@v5
            -   uses: php-actions/phpunit@v3
                with:
                    php_extensions: xdebug
                    bootstrap: tests/bootstrap.php
                    configuration: phpunit.xml.dist

